### ISSUE TITLE
Implement DNS name validation

### ISSUE THREAD

**Issue by keeganwitt** [spiffe/spire-controller-manager#121]
pkg/spireentry/entries.go has

```go
func validateDNSName(dnsName string) error {
	// TODO:
	return nil
}
```

We should implement DNS name validation to make sure that the name doesn't exceed the 128-character total limit or the 63-character subdomain limit.

**Comment by vivekvamsi-VV** [comment]
@keeganwitt I can take this up

**Comment by vivekvamsi-VV** [comment]
Hey @keeganwitt , just to follow up & check real quick - Is this something that is still needed to be worked on?

**Comment by keeganwitt** [comment]
Yes. To my knowledge, without this, there is nothing preventing invalid DNS information from being placed into x509 certificates that are created by SPIRE when you've configured an entry that violates the DNS spec.

**Comment by faisal-memon** [comment]
We discussed on a contributer sync that the spire server would reject any invalid dns names so an additional check was not needed. cc @azdagron

**Comment by azdagron** [comment]
Yep, @faisal-memon is correct. SPIRE server will reject entries with malformed DNS names. The benefit of implementing this check could possibly be earlier detection of a problem but it's actually hard to do because we don't know what the names are until rendering the template for a given pod, so doing this early enough for it to make a difference feels impractical? Failure to create the entry will show up in the CRD status though.

**Comment by keeganwitt** [comment]
It looks like the validation was planned to be against the rendered name (https://github.com/spiffe/spire-controller-manager/blob/9ae90ef83ba5550a707ef8aba7968b19eec4a8a4/pkg/spireentry/entries.go#L154). I'm not sure if this was done to copy the way Registrar did it or what.

I'm OK with relying on the server validation as long as the error is clear. I mostly created this issue to capture the TODO and not for any particular use case I had.
