### ISSUE TITLE
What's the difference between this project and  k8s-workload-registrar in the spire repo

### ISSUE THREAD

**Issue by itomsawyer** [spiffe/spire-controller-manager#35]
As the title mentioned, it's wired for me to have two k8s operator manager. 

I wonder how to choose the right one to use, thx.

**Comment by azdagron** [comment]
There is some history here :) The k8s-workload-registrar in the SPIRE repository was the initial effort to provide automatic workload registration for workloads running inside Kubernetes. That component become somewhat of a playground for the community in developing and trying out different methods of tracking changes to workloads and reconciling the registration entries on SPIRE. This lead to three different operational modes, one of which  (webhook mode) has been since removed due to lack of robustness in the approach. Several lessons were learned along the way.

The spire-controller-manager is another approach to workload registration in K8s that takes in the lessons learned. We believe it presents a reasonable way to declare and register workload identities and we have been promoting it over the k8s-workload-registrar for new deployments. We plan to deprecate the k8s-workload-registrar in favor of the spire-controller-manager.

**Comment by itomsawyer** [comment]
Thanks for replying, I got the point. 

For now ,I believe the performance of spire-controller-manager has a lot of space to improve. 
Meanwhile, If spire-controller-manager is used for automatic workload registration, there's no way for administrator to create registry entry manually because spire-controller-manager will automatically delete entries that are not controlled by spire-controller-manager

**Comment by azdagron** [comment]
> I believe the performance of spire-controller-manager has a lot of space to improve.

I'd love to hear about your experience so far. What performance issues have you noticed?

> there's no way for administrator to create registry entry manually because spire-controller-manager will automatically delete entries

Yes, this is a known limitation. We've considered adding a "registrant" field to registration entries on SPIRE to allow components such as this to know if an entry is one they should be managing.

**Comment by itomsawyer** [comment]
@azdagron sorry for the delay of replying. 

> Can you further expand on your use case for mixing manual registration with the automatic registration provided by the controller?

For now, each pod with a valid spiffeid selectors matched will be assigned to a register entry and the entry's parentID is set to the spire-agent on the node which the pod is running.  These pods may share the same spiffeID, for example,  the backend of a web server can be deployed with a deployment which replicas it set to 10. I want to reduce the number of registered entries to a single one. First of all , I need to register a spiffeID for spire-agent which can cover all of these pod is running.  Unfortunately, I can not do so.

**Comment by itomsawyer** [comment]
> I'd love to hear about your experience so far. What performance issues have you noticed?

1. Each pod reconcile will trigger all clusterspiffeid to be reconciled, but it is not always required. Because each clusterspiffeid has its namespace selectors and pod selectors, the current reconciled pod may be not related to any of lusterspiffeid 
2. During each of clusterspiffeid reconile procedure , the text/template of clusterspiffeid is parsed. I think it can be cached and do filtering the pod we concerned in pod reconcile

**Comment by itomsawyer** [comment]
Furthermore, as I read the docs of [spiffeID of agent](https://spiffe.io/docs/latest/deploying/registering/#1-defining-the-spiffe-id-of-the-agent). I think one goal of spiffeID of agent is to provide a method to  make a group of nodes instead of use every node as a individual one.  We lost this ability due to we cannot register entries manually.

**Comment by azdagron** [comment]
The current design was intentional. The first iteration tried to be more selective about what exactly was reconciled, but this led to more complex and fragile code. I decided to start with a simpler algorithm which valued correctness, at the cost of some wasted cycles. This does mean that more code executes than is strictly necessary but I'd be curious to know if this has actually led to a substantive negative impact on performance. How have you observed these performance issues? High CPU load? Increased latency? Have you profiled the code to determine the hotspots?

> Because each clusterspiffeid has its namespace selectors and pod selectors, the current reconciled pod may be not related to any of lusterspiffeid

I'm not sure this is true. The pods which was previously selected by a ClusterSPIFFEID may have had its labels updated such that it no longer matches any ClusterSPIFFEID resources. In this case we still want to reconcile so that we can clean up the entry related to that pod.

> During each of clusterspiffeid reconile procedure , the text/template of clusterspiffeid is parsed. I think it can be cached and do filtering the pod we concerned in pod reconcile

This is true, we could probably come up with a way to cache the templates. I'd want to wait until we saw in a CPU profile before introducing that complexity though.

> Furthermore, as I read the docs of [spiffeID of agent](https://spiffe.io/docs/latest/deploying/registering/#1-defining-the-spiffe-id-of-the-agent). I think one goal of spiffeID of agent is to provide a method to make a group of nodes instead of use every node as a individual one. We lost this ability due to we cannot register entries manually.

Aliasing is certainly useful for creating a group of nodes that can all run the same set of workloads. However, the only reason to alias is if you are manually registering workloads that are not otherwise being registered by the spire-controller-manager. Do you have non-k8s workloads or workloads that cannot otherwise be targeted by the spire-controller-manager that you are wanting to register?

**Comment by azdagron** [comment]
Thank you for this discussion @itomsawyer. I'm going to go ahead and close this issue for now.

If there is individual feature requests or bug reports, let's file and track those in separate, distinct issues.

**Comment by kfox1111** [comment]
I cant speak for the others, but those optimizations sound really good to me. 

@MarcosDY can you please weigh in too?
